/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CountryCode: typeof import('./components/CountryCode.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Link: typeof import('./components/Link.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    PasswordLogin: typeof import('./components/PasswordLogin.vue')['default']
    Player: typeof import('./components/Player.vue')['default']
    PlayerBar: typeof import('./components/PlayerBar.vue')['default']
    PlayProgressBar: typeof import('./components/PlayProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SMSLogin: typeof import('./components/SMSLogin.vue')['default']
    VolumeKey: typeof import('./components/VolumeKey.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
